version: '2'
services:
  skyscape:
    container_name: skyscape-db
    image: knw1234/mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
