name: buildx

on:
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USER: knw1234
  DOCKER_IMAGE_NAME: knw1234/mariadb
  GHCR_IMAGE_NAME: motolies/mariadb

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      -
        name: Buildx and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.ENV_MARIADB_VERSION }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:latest
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ env.ENV_MARIADB_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            MARIADB_VERSION=${{ env.ENV_MARIADB_VERSION }}
            BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
          push: true